name: Deploy Backend to Azure

on:
  push:
    branches: [ main ]
    paths:
      - 'recruitment-portal-backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: |
        cd recruitment-portal-backend
        npm install

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'flow-recruit-aegneqdbe0b3dwgu' # Updated to match full app name
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./recruitment-portal-backend