name: Set up Node.js
  uses: actions/setup-node@v3
  with:
    node-version: '20.x'

name: Install dependencies
  run: |
    cd recruitment-portal-backend
    npm ci

name: Prepare deployment package
  run: |
    cd recruitment-portal-backend
    # Create the web.config file if not already present

name: Deploy to Azure Web App
  uses: azure/webapps-deploy@v2
  with:
    app-name: 'flow-recruit'
    publish-profile: ${{ secrets.AZURE_WEBAPP }}
    package: ./recruitment-portal-backend
